namespace trainer_template
{
	// Token: 0x0200001E RID: 30
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000163 RID: 355 RVA: 0x0000CBB8 File Offset: 0x0000ADB8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000164 RID: 356 RVA: 0x0000CBFC File Offset: 0x0000ADFC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::trainer_template.Form1));
			this.health_timer = new global::System.Windows.Forms.Timer(this.components);
			this.Hotkey_timer = new global::System.Windows.Forms.Timer(this.components);
			this.mana_timer = new global::System.Windows.Forms.Timer(this.components);
			this.oxygen_timer = new global::System.Windows.Forms.Timer(this.components);
			this.speed_timer = new global::System.Windows.Forms.Timer(this.components);
			this.game_checker = new global::System.Windows.Forms.Timer(this.components);
			this.FormSkin1 = new global::trainer_template.FormSkin();
			this.FlatTabControl1 = new global::trainer_template.FlatTabControl();
			this.trainer_tab = new global::System.Windows.Forms.TabPage();
			this.trainer_st_lbl = new global::trainer_template.FlatLabel();
			this.trainer_status_btn = new global::trainer_template.FlatToggle();
			this.enable_trainer_lbl = new global::trainer_template.FlatLabel();
			this.numpad8_lbl = new global::trainer_template.FlatLabel();
			this.LogInSeperator1 = new global::trainer_template.LogInSeperator();
			this.numpad7_lbl = new global::trainer_template.FlatLabel();
			this.numpad1_lbl = new global::trainer_template.FlatLabel();
			this.numpad6_lbl = new global::trainer_template.FlatLabel();
			this.numpad1_toggle = new global::trainer_template.FlatToggle();
			this.numpad5_lbl = new global::trainer_template.FlatLabel();
			this.health_lbl = new global::trainer_template.FlatLabel();
			this.numpad4_lbl = new global::trainer_template.FlatLabel();
			this.numpad2_toggle = new global::trainer_template.FlatToggle();
			this.numpad3_lbl = new global::trainer_template.FlatLabel();
			this.numpad3_toggle = new global::trainer_template.FlatToggle();
			this.numpad2_lbl = new global::trainer_template.FlatLabel();
			this.FlatLabel10 = new global::trainer_template.FlatLabel();
			this.FlatLabel4 = new global::trainer_template.FlatLabel();
			this.numpad7_toggle = new global::trainer_template.FlatToggle();
			this.FlatLabel5 = new global::trainer_template.FlatLabel();
			this.FlatLabel9 = new global::trainer_template.FlatLabel();
			this.numpad4_toggle = new global::trainer_template.FlatToggle();
			this.numpad6_toggle = new global::trainer_template.FlatToggle();
			this.stealth_lbl = new global::trainer_template.FlatLabel();
			this.numpad5_toggle = new global::trainer_template.FlatToggle();
			this.FlatLabel8 = new global::trainer_template.FlatLabel();
			this.numpad8_toggle = new global::trainer_template.FlatToggle();
			this.speed_lbl = new global::trainer_template.FlatLabel();
			this.md5_tab = new global::System.Windows.Forms.TabPage();
			this.filepath_txt = new global::trainer_template.FlatTextBox();
			this.Check_btn = new global::trainer_template.FlatButton();
			this.your_hash_lbl = new global::trainer_template.FlatLabel();
			this.game_hash_lbl = new global::trainer_template.FlatLabel();
			this.your_hash_txt = new global::trainer_template.FlatTextBox();
			this.game_hash_txt = new global::trainer_template.FlatTextBox();
			this.md5_alter_box = new global::trainer_template.FlatAlertBox();
			this.trn_settings_tab = new global::System.Windows.Forms.TabPage();
			this.language_sel_lbl = new global::trainer_template.FlatLabel();
			this.LogInSeperator3 = new global::trainer_template.LogInSeperator();
			this.toggle_btn_lbl = new global::trainer_template.FlatLabel();
			this.toggle_btn = new global::trainer_template.FlatToggle();
			this.enb_hotkey_lbl = new global::trainer_template.FlatLabel();
			this.Hotkey_toggle = new global::trainer_template.FlatToggle();
			this.german_lang = new global::System.Windows.Forms.PictureBox();
			this.russian_lang = new global::System.Windows.Forms.PictureBox();
			this.english_lang = new global::System.Windows.Forms.PictureBox();
			this.game_status_bar = new global::trainer_template.FlatStatusBar();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.trainer_sts_lbl = new global::trainer_template.LogInLabel();
			this.getGameID_lbl = new global::trainer_template.LogInLabel();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.FlatClose1 = new global::trainer_template.FlatClose();
			this.FlatMini1 = new global::trainer_template.FlatMini();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.FormSkin1.SuspendLayout();
			this.FlatTabControl1.SuspendLayout();
			this.trainer_tab.SuspendLayout();
			this.md5_tab.SuspendLayout();
			this.trn_settings_tab.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.german_lang).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.russian_lang).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.english_lang).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			base.SuspendLayout();
			this.health_timer.Interval = 20;
			this.Hotkey_timer.Enabled = true;
			this.Hotkey_timer.Interval = 20;
			this.mana_timer.Interval = 20;
			this.oxygen_timer.Interval = 20;
			this.speed_timer.Interval = 10;
			this.FormSkin1.BackColor = global::System.Drawing.Color.FromArgb(51, 51, 51);
			this.FormSkin1.BaseColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FormSkin1.BorderColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FormSkin1.Controls.Add(this.FlatTabControl1);
			this.FormSkin1.Controls.Add(this.game_status_bar);
			this.FormSkin1.Controls.Add(this.PictureBox2);
			this.FormSkin1.Controls.Add(this.trainer_sts_lbl);
			this.FormSkin1.Controls.Add(this.getGameID_lbl);
			this.FormSkin1.Controls.Add(this.PictureBox1);
			this.FormSkin1.Controls.Add(this.FlatClose1);
			this.FormSkin1.Controls.Add(this.FlatMini1);
			this.FormSkin1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.FormSkin1.FlatColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FormSkin1.Font = new global::System.Drawing.Font("Segoe UI", 12f);
			this.FormSkin1.HeaderColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FormSkin1.HeaderMaximize = false;
			this.FormSkin1.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			this.FormSkin1.Location = new global::System.Drawing.Point(0, 0);
			this.FormSkin1.Name = "FormSkin1";
			this.FormSkin1.Size = new global::System.Drawing.Size(963, 465);
			this.FormSkin1.TabIndex = 0;
			this.FormSkin1.Text = "Dishonored - Game of the Year Edition Trainer by SeryogaSK";
			this.FlatTabControl1.ActiveColor = global::System.Drawing.Color.FromArgb(0, 170, 220);
			this.FlatTabControl1.BaseColor = global::System.Drawing.Color.FromArgb(45, 47, 49);
			this.FlatTabControl1.Controls.Add(this.trainer_tab);
			this.FlatTabControl1.Controls.Add(this.md5_tab);
			this.FlatTabControl1.Controls.Add(this.trn_settings_tab);
			this.FlatTabControl1.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatTabControl1.ItemSize = new global::System.Drawing.Size(120, 40);
			this.FlatTabControl1.Location = new global::System.Drawing.Point(215, 46);
			this.FlatTabControl1.Name = "FlatTabControl1";
			this.FlatTabControl1.SelectedIndex = 0;
			this.FlatTabControl1.Size = new global::System.Drawing.Size(739, 329);
			this.FlatTabControl1.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
			this.FlatTabControl1.TabIndex = 1055;
			this.trainer_tab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.trainer_tab.Controls.Add(this.trainer_st_lbl);
			this.trainer_tab.Controls.Add(this.trainer_status_btn);
			this.trainer_tab.Controls.Add(this.enable_trainer_lbl);
			this.trainer_tab.Controls.Add(this.numpad8_lbl);
			this.trainer_tab.Controls.Add(this.LogInSeperator1);
			this.trainer_tab.Controls.Add(this.numpad7_lbl);
			this.trainer_tab.Controls.Add(this.numpad1_lbl);
			this.trainer_tab.Controls.Add(this.numpad6_lbl);
			this.trainer_tab.Controls.Add(this.numpad1_toggle);
			this.trainer_tab.Controls.Add(this.numpad5_lbl);
			this.trainer_tab.Controls.Add(this.health_lbl);
			this.trainer_tab.Controls.Add(this.numpad4_lbl);
			this.trainer_tab.Controls.Add(this.numpad2_toggle);
			this.trainer_tab.Controls.Add(this.numpad3_lbl);
			this.trainer_tab.Controls.Add(this.numpad3_toggle);
			this.trainer_tab.Controls.Add(this.numpad2_lbl);
			this.trainer_tab.Controls.Add(this.FlatLabel10);
			this.trainer_tab.Controls.Add(this.FlatLabel4);
			this.trainer_tab.Controls.Add(this.numpad7_toggle);
			this.trainer_tab.Controls.Add(this.FlatLabel5);
			this.trainer_tab.Controls.Add(this.FlatLabel9);
			this.trainer_tab.Controls.Add(this.numpad4_toggle);
			this.trainer_tab.Controls.Add(this.numpad6_toggle);
			this.trainer_tab.Controls.Add(this.stealth_lbl);
			this.trainer_tab.Controls.Add(this.numpad5_toggle);
			this.trainer_tab.Controls.Add(this.FlatLabel8);
			this.trainer_tab.Controls.Add(this.numpad8_toggle);
			this.trainer_tab.Controls.Add(this.speed_lbl);
			this.trainer_tab.Location = new global::System.Drawing.Point(4, 44);
			this.trainer_tab.Name = "trainer_tab";
			this.trainer_tab.Padding = new global::System.Windows.Forms.Padding(3);
			this.trainer_tab.Size = new global::System.Drawing.Size(731, 281);
			this.trainer_tab.TabIndex = 0;
			this.trainer_tab.Text = "Trainer";
			this.trainer_st_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.trainer_st_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.trainer_st_lbl.ForeColor = global::System.Drawing.Color.White;
			this.trainer_st_lbl.Location = new global::System.Drawing.Point(212, 12);
			this.trainer_st_lbl.Name = "trainer_st_lbl";
			this.trainer_st_lbl.Size = new global::System.Drawing.Size(35, 33);
			this.trainer_st_lbl.TabIndex = 1043;
			this.trainer_st_lbl.Text = "INS";
			this.trainer_st_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.trainer_status_btn.BackColor = global::System.Drawing.Color.Transparent;
			this.trainer_status_btn.Checked = false;
			this.trainer_status_btn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.trainer_status_btn.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.trainer_status_btn.Location = new global::System.Drawing.Point(253, 12);
			this.trainer_status_btn.Name = "trainer_status_btn";
			this.trainer_status_btn.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.trainer_status_btn.Size = new global::System.Drawing.Size(76, 33);
			this.trainer_status_btn.TabIndex = 1042;
			this.trainer_status_btn.Text = "Trainer Status Btn";
			this.enable_trainer_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.enable_trainer_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.enable_trainer_lbl.ForeColor = global::System.Drawing.Color.White;
			this.enable_trainer_lbl.Location = new global::System.Drawing.Point(335, 12);
			this.enable_trainer_lbl.Name = "enable_trainer_lbl";
			this.enable_trainer_lbl.Size = new global::System.Drawing.Size(128, 33);
			this.enable_trainer_lbl.TabIndex = 1044;
			this.enable_trainer_lbl.Text = "ENABLE TRAINER";
			this.enable_trainer_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad8_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad8_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad8_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad8_lbl.Location = new global::System.Drawing.Point(311, 150);
			this.numpad8_lbl.Name = "numpad8_lbl";
			this.numpad8_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad8_lbl.TabIndex = 1052;
			this.numpad8_lbl.Text = "NUM 8";
			this.numpad8_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.LogInSeperator1.Alignment = global::trainer_template.LogInSeperator.Style.Horizontal;
			this.LogInSeperator1.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInSeperator1.Location = new global::System.Drawing.Point(-2, 49);
			this.LogInSeperator1.Name = "LogInSeperator1";
			this.LogInSeperator1.SeperatorColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInSeperator1.Size = new global::System.Drawing.Size(814, 20);
			this.LogInSeperator1.TabIndex = 1045;
			this.LogInSeperator1.Text = "LogInSeperator1";
			this.LogInSeperator1.Thickness = 1f;
			this.numpad7_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad7_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad7_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad7_lbl.Location = new global::System.Drawing.Point(311, 111);
			this.numpad7_lbl.Name = "numpad7_lbl";
			this.numpad7_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad7_lbl.TabIndex = 1051;
			this.numpad7_lbl.Text = "NUM 7";
			this.numpad7_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad1_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad1_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad1_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad1_lbl.Location = new global::System.Drawing.Point(10, 72);
			this.numpad1_lbl.Name = "numpad1_lbl";
			this.numpad1_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad1_lbl.TabIndex = 1041;
			this.numpad1_lbl.Text = "NUM 1";
			this.numpad1_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad6_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad6_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad6_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad6_lbl.Location = new global::System.Drawing.Point(311, 72);
			this.numpad6_lbl.Name = "numpad6_lbl";
			this.numpad6_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad6_lbl.TabIndex = 1050;
			this.numpad6_lbl.Text = "NUM 6";
			this.numpad6_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad1_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad1_toggle.Checked = false;
			this.numpad1_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad1_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad1_toggle.Location = new global::System.Drawing.Point(71, 72);
			this.numpad1_toggle.Name = "numpad1_toggle";
			this.numpad1_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad1_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad1_toggle.TabIndex = 1010;
			this.numpad1_toggle.Text = "health_btn";
			this.numpad5_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad5_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad5_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad5_lbl.Location = new global::System.Drawing.Point(10, 229);
			this.numpad5_lbl.Name = "numpad5_lbl";
			this.numpad5_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad5_lbl.TabIndex = 1049;
			this.numpad5_lbl.Text = "NUM 5";
			this.numpad5_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.health_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.health_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.health_lbl.ForeColor = global::System.Drawing.Color.White;
			this.health_lbl.Location = new global::System.Drawing.Point(153, 72);
			this.health_lbl.Name = "health_lbl";
			this.health_lbl.Size = new global::System.Drawing.Size(140, 33);
			this.health_lbl.TabIndex = 1012;
			this.health_lbl.Text = "UNL. HEALTH";
			this.health_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad4_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad4_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad4_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad4_lbl.Location = new global::System.Drawing.Point(10, 189);
			this.numpad4_lbl.Name = "numpad4_lbl";
			this.numpad4_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad4_lbl.TabIndex = 1048;
			this.numpad4_lbl.Text = "NUM 4";
			this.numpad4_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad2_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad2_toggle.Checked = false;
			this.numpad2_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad2_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad2_toggle.Location = new global::System.Drawing.Point(71, 111);
			this.numpad2_toggle.Name = "numpad2_toggle";
			this.numpad2_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad2_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad2_toggle.TabIndex = 1014;
			this.numpad2_toggle.Text = "FlatToggle1";
			this.numpad3_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad3_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad3_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad3_lbl.Location = new global::System.Drawing.Point(10, 150);
			this.numpad3_lbl.Name = "numpad3_lbl";
			this.numpad3_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad3_lbl.TabIndex = 1047;
			this.numpad3_lbl.Text = "NUM 3";
			this.numpad3_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad3_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad3_toggle.Checked = false;
			this.numpad3_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad3_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad3_toggle.Location = new global::System.Drawing.Point(71, 150);
			this.numpad3_toggle.Name = "numpad3_toggle";
			this.numpad3_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad3_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad3_toggle.TabIndex = 1015;
			this.numpad3_toggle.Text = "FlatToggle2";
			this.numpad2_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad2_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad2_lbl.ForeColor = global::System.Drawing.Color.White;
			this.numpad2_lbl.Location = new global::System.Drawing.Point(10, 111);
			this.numpad2_lbl.Name = "numpad2_lbl";
			this.numpad2_lbl.Size = new global::System.Drawing.Size(55, 33);
			this.numpad2_lbl.TabIndex = 1046;
			this.numpad2_lbl.Text = "NUM 2";
			this.numpad2_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.FlatLabel10.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel10.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.FlatLabel10.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatLabel10.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel10.Location = new global::System.Drawing.Point(454, 111);
			this.FlatLabel10.Name = "FlatLabel10";
			this.FlatLabel10.Size = new global::System.Drawing.Size(140, 33);
			this.FlatLabel10.TabIndex = 1030;
			this.FlatLabel10.Text = "NO RELOAD";
			this.FlatLabel10.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.FlatLabel4.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel4.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatLabel4.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel4.Location = new global::System.Drawing.Point(153, 111);
			this.FlatLabel4.Name = "FlatLabel4";
			this.FlatLabel4.Size = new global::System.Drawing.Size(140, 33);
			this.FlatLabel4.TabIndex = 1016;
			this.FlatLabel4.Text = "UNL. MANA";
			this.FlatLabel4.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad7_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad7_toggle.Checked = false;
			this.numpad7_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad7_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad7_toggle.Location = new global::System.Drawing.Point(372, 111);
			this.numpad7_toggle.Name = "numpad7_toggle";
			this.numpad7_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad7_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad7_toggle.TabIndex = 1029;
			this.numpad7_toggle.Text = "FlatToggle2";
			this.FlatLabel5.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel5.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatLabel5.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel5.Location = new global::System.Drawing.Point(153, 150);
			this.FlatLabel5.Name = "FlatLabel5";
			this.FlatLabel5.Size = new global::System.Drawing.Size(140, 33);
			this.FlatLabel5.TabIndex = 1017;
			this.FlatLabel5.Text = "UNL. OXYGEN";
			this.FlatLabel5.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.FlatLabel9.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel9.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatLabel9.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel9.Location = new global::System.Drawing.Point(454, 72);
			this.FlatLabel9.Name = "FlatLabel9";
			this.FlatLabel9.Size = new global::System.Drawing.Size(140, 33);
			this.FlatLabel9.TabIndex = 1028;
			this.FlatLabel9.Text = "UNL. AMMO";
			this.FlatLabel9.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad4_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad4_toggle.Checked = false;
			this.numpad4_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad4_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad4_toggle.Location = new global::System.Drawing.Point(71, 189);
			this.numpad4_toggle.Name = "numpad4_toggle";
			this.numpad4_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad4_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad4_toggle.TabIndex = 1021;
			this.numpad4_toggle.Text = "FlatToggle2";
			this.numpad6_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad6_toggle.Checked = false;
			this.numpad6_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad6_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad6_toggle.Location = new global::System.Drawing.Point(372, 72);
			this.numpad6_toggle.Name = "numpad6_toggle";
			this.numpad6_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad6_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad6_toggle.TabIndex = 1027;
			this.numpad6_toggle.Text = "FlatToggle2";
			this.stealth_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.stealth_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.stealth_lbl.ForeColor = global::System.Drawing.Color.White;
			this.stealth_lbl.Location = new global::System.Drawing.Point(153, 189);
			this.stealth_lbl.Name = "stealth_lbl";
			this.stealth_lbl.Size = new global::System.Drawing.Size(140, 33);
			this.stealth_lbl.TabIndex = 1022;
			this.stealth_lbl.Text = "STEALTH";
			this.stealth_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad5_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad5_toggle.Checked = false;
			this.numpad5_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad5_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad5_toggle.Location = new global::System.Drawing.Point(71, 228);
			this.numpad5_toggle.Name = "numpad5_toggle";
			this.numpad5_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad5_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad5_toggle.TabIndex = 1024;
			this.numpad5_toggle.Text = "FlatToggle2";
			this.FlatLabel8.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel8.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatLabel8.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel8.Location = new global::System.Drawing.Point(153, 228);
			this.FlatLabel8.Name = "FlatLabel8";
			this.FlatLabel8.Size = new global::System.Drawing.Size(140, 33);
			this.FlatLabel8.TabIndex = 1026;
			this.FlatLabel8.Text = "UNL. MONEY/RUNS";
			this.FlatLabel8.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.numpad8_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.numpad8_toggle.Checked = false;
			this.numpad8_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.numpad8_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.numpad8_toggle.Location = new global::System.Drawing.Point(372, 150);
			this.numpad8_toggle.Name = "numpad8_toggle";
			this.numpad8_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.numpad8_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.numpad8_toggle.TabIndex = 1018;
			this.numpad8_toggle.Text = "FlatToggle2";
			this.speed_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.speed_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.speed_lbl.ForeColor = global::System.Drawing.Color.White;
			this.speed_lbl.Location = new global::System.Drawing.Point(454, 150);
			this.speed_lbl.Name = "speed_lbl";
			this.speed_lbl.Size = new global::System.Drawing.Size(233, 33);
			this.speed_lbl.TabIndex = 1019;
			this.speed_lbl.Text = "SUPER SPEED";
			this.speed_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.md5_tab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.md5_tab.Controls.Add(this.filepath_txt);
			this.md5_tab.Controls.Add(this.Check_btn);
			this.md5_tab.Controls.Add(this.your_hash_lbl);
			this.md5_tab.Controls.Add(this.game_hash_lbl);
			this.md5_tab.Controls.Add(this.your_hash_txt);
			this.md5_tab.Controls.Add(this.game_hash_txt);
			this.md5_tab.Controls.Add(this.md5_alter_box);
			this.md5_tab.Location = new global::System.Drawing.Point(4, 44);
			this.md5_tab.Name = "md5_tab";
			this.md5_tab.Padding = new global::System.Windows.Forms.Padding(3);
			this.md5_tab.Size = new global::System.Drawing.Size(731, 281);
			this.md5_tab.TabIndex = 1;
			this.md5_tab.Text = "MD5 Checker";
			this.filepath_txt.BackColor = global::System.Drawing.Color.Transparent;
			this.filepath_txt.Location = new global::System.Drawing.Point(538, 157);
			this.filepath_txt.MaxLength = 32767;
			this.filepath_txt.Multiline = false;
			this.filepath_txt.Name = "filepath_txt";
			this.filepath_txt.ReadOnly = false;
			this.filepath_txt.Size = new global::System.Drawing.Size(75, 29);
			this.filepath_txt.TabIndex = 1061;
			this.filepath_txt.Text = "filepath_txt";
			this.filepath_txt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.filepath_txt.TextColor = global::System.Drawing.Color.FromArgb(192, 192, 192);
			this.filepath_txt.UseSystemPasswordChar = false;
			this.filepath_txt.Visible = false;
			this.Check_btn.BackColor = global::System.Drawing.Color.Transparent;
			this.Check_btn.BaseColor = global::System.Drawing.Color.FromArgb(0, 170, 220);
			this.Check_btn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Check_btn.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.Check_btn.Location = new global::System.Drawing.Point(619, 154);
			this.Check_btn.Name = "Check_btn";
			this.Check_btn.Rounded = false;
			this.Check_btn.Size = new global::System.Drawing.Size(106, 32);
			this.Check_btn.TabIndex = 1060;
			this.Check_btn.Text = "Select EXE";
			this.Check_btn.TextColor = global::System.Drawing.Color.FromArgb(243, 243, 243);
			this.your_hash_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.your_hash_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.your_hash_lbl.ForeColor = global::System.Drawing.Color.White;
			this.your_hash_lbl.Location = new global::System.Drawing.Point(2, 83);
			this.your_hash_lbl.Name = "your_hash_lbl";
			this.your_hash_lbl.Size = new global::System.Drawing.Size(158, 33);
			this.your_hash_lbl.TabIndex = 1059;
			this.your_hash_lbl.Text = "Your EXE Hash:";
			this.your_hash_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.game_hash_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.game_hash_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.game_hash_lbl.ForeColor = global::System.Drawing.Color.White;
			this.game_hash_lbl.Location = new global::System.Drawing.Point(2, 14);
			this.game_hash_lbl.Name = "game_hash_lbl";
			this.game_hash_lbl.Size = new global::System.Drawing.Size(158, 33);
			this.game_hash_lbl.TabIndex = 1058;
			this.game_hash_lbl.Text = "Trainer EXE Hash:";
			this.game_hash_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.your_hash_txt.BackColor = global::System.Drawing.Color.Transparent;
			this.your_hash_txt.Location = new global::System.Drawing.Point(6, 119);
			this.your_hash_txt.MaxLength = 32767;
			this.your_hash_txt.Multiline = false;
			this.your_hash_txt.Name = "your_hash_txt";
			this.your_hash_txt.ReadOnly = true;
			this.your_hash_txt.Size = new global::System.Drawing.Size(719, 29);
			this.your_hash_txt.TabIndex = 2;
			this.your_hash_txt.Text = "Your Hash";
			this.your_hash_txt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.your_hash_txt.TextColor = global::System.Drawing.Color.FromArgb(192, 192, 192);
			this.your_hash_txt.UseSystemPasswordChar = false;
			this.game_hash_txt.BackColor = global::System.Drawing.Color.Transparent;
			this.game_hash_txt.Location = new global::System.Drawing.Point(6, 50);
			this.game_hash_txt.MaxLength = 32767;
			this.game_hash_txt.Multiline = false;
			this.game_hash_txt.Name = "game_hash_txt";
			this.game_hash_txt.ReadOnly = true;
			this.game_hash_txt.Size = new global::System.Drawing.Size(719, 29);
			this.game_hash_txt.TabIndex = 1;
			this.game_hash_txt.Text = "Trainer Hash";
			this.game_hash_txt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.game_hash_txt.TextColor = global::System.Drawing.Color.FromArgb(192, 192, 192);
			this.game_hash_txt.UseSystemPasswordChar = false;
			this.md5_alter_box.BackColor = global::System.Drawing.Color.FromArgb(60, 70, 73);
			this.md5_alter_box.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.md5_alter_box.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.md5_alter_box.kind = global::trainer_template.FlatAlertBox._Kind.Info;
			this.md5_alter_box.Location = new global::System.Drawing.Point(6, 154);
			this.md5_alter_box.Name = "md5_alter_box";
			this.md5_alter_box.Size = new global::System.Drawing.Size(578, 42);
			this.md5_alter_box.TabIndex = 0;
			this.md5_alter_box.Text = "Please Select your Game EXE first";
			this.md5_alter_box.Visible = false;
			this.trn_settings_tab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.trn_settings_tab.Controls.Add(this.language_sel_lbl);
			this.trn_settings_tab.Controls.Add(this.LogInSeperator3);
			this.trn_settings_tab.Controls.Add(this.toggle_btn_lbl);
			this.trn_settings_tab.Controls.Add(this.toggle_btn);
			this.trn_settings_tab.Controls.Add(this.enb_hotkey_lbl);
			this.trn_settings_tab.Controls.Add(this.Hotkey_toggle);
			this.trn_settings_tab.Controls.Add(this.german_lang);
			this.trn_settings_tab.Controls.Add(this.russian_lang);
			this.trn_settings_tab.Controls.Add(this.english_lang);
			this.trn_settings_tab.Location = new global::System.Drawing.Point(4, 44);
			this.trn_settings_tab.Name = "trn_settings_tab";
			this.trn_settings_tab.Size = new global::System.Drawing.Size(731, 281);
			this.trn_settings_tab.TabIndex = 2;
			this.trn_settings_tab.Text = "Trainer Settings";
			this.language_sel_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.language_sel_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.language_sel_lbl.ForeColor = global::System.Drawing.Color.White;
			this.language_sel_lbl.Location = new global::System.Drawing.Point(-1, 65);
			this.language_sel_lbl.Name = "language_sel_lbl";
			this.language_sel_lbl.Size = new global::System.Drawing.Size(117, 23);
			this.language_sel_lbl.TabIndex = 1057;
			this.language_sel_lbl.Text = "Trainer Language:";
			this.language_sel_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.LogInSeperator3.Alignment = global::trainer_template.LogInSeperator.Style.Horizontal;
			this.LogInSeperator3.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInSeperator3.Location = new global::System.Drawing.Point(-18, 42);
			this.LogInSeperator3.Name = "LogInSeperator3";
			this.LogInSeperator3.SeperatorColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInSeperator3.Size = new global::System.Drawing.Size(814, 20);
			this.LogInSeperator3.TabIndex = 1054;
			this.LogInSeperator3.Text = "LogInSeperator3";
			this.LogInSeperator3.Thickness = 1f;
			this.toggle_btn_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.toggle_btn_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.toggle_btn_lbl.ForeColor = global::System.Drawing.Color.White;
			this.toggle_btn_lbl.Location = new global::System.Drawing.Point(389, 3);
			this.toggle_btn_lbl.Name = "toggle_btn_lbl";
			this.toggle_btn_lbl.Size = new global::System.Drawing.Size(205, 33);
			this.toggle_btn_lbl.TabIndex = 1056;
			this.toggle_btn_lbl.Text = "ENABLE TOGGLE BUTTONS";
			this.toggle_btn_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.toggle_btn.BackColor = global::System.Drawing.Color.Transparent;
			this.toggle_btn.Checked = false;
			this.toggle_btn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.toggle_btn.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.toggle_btn.Location = new global::System.Drawing.Point(307, 3);
			this.toggle_btn.Name = "toggle_btn";
			this.toggle_btn.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.toggle_btn.Size = new global::System.Drawing.Size(76, 33);
			this.toggle_btn.TabIndex = 1055;
			this.toggle_btn.Text = "Toggle ON/OFF";
			this.enb_hotkey_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.enb_hotkey_lbl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.enb_hotkey_lbl.ForeColor = global::System.Drawing.Color.White;
			this.enb_hotkey_lbl.Location = new global::System.Drawing.Point(85, 3);
			this.enb_hotkey_lbl.Name = "enb_hotkey_lbl";
			this.enb_hotkey_lbl.Size = new global::System.Drawing.Size(150, 33);
			this.enb_hotkey_lbl.TabIndex = 1054;
			this.enb_hotkey_lbl.Text = "ENABLE HOTKEY";
			this.enb_hotkey_lbl.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Hotkey_toggle.BackColor = global::System.Drawing.Color.Transparent;
			this.Hotkey_toggle.Checked = false;
			this.Hotkey_toggle.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Hotkey_toggle.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.Hotkey_toggle.Location = new global::System.Drawing.Point(3, 3);
			this.Hotkey_toggle.Name = "Hotkey_toggle";
			this.Hotkey_toggle.Options = global::trainer_template.FlatToggle._Options.Style3;
			this.Hotkey_toggle.Size = new global::System.Drawing.Size(76, 33);
			this.Hotkey_toggle.TabIndex = 0;
			this.Hotkey_toggle.Text = "Hotkey ON/OFF";
			this.german_lang.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("german_lang.Image");
			this.german_lang.Location = new global::System.Drawing.Point(122, 72);
			this.german_lang.Name = "german_lang";
			this.german_lang.Size = new global::System.Drawing.Size(16, 16);
			this.german_lang.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.german_lang.TabIndex = 1035;
			this.german_lang.TabStop = false;
			this.russian_lang.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("russian_lang.Image");
			this.russian_lang.Location = new global::System.Drawing.Point(144, 72);
			this.russian_lang.Name = "russian_lang";
			this.russian_lang.Size = new global::System.Drawing.Size(16, 16);
			this.russian_lang.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.russian_lang.TabIndex = 1034;
			this.russian_lang.TabStop = false;
			this.english_lang.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("english_lang.Image");
			this.english_lang.Location = new global::System.Drawing.Point(169, 72);
			this.english_lang.Name = "english_lang";
			this.english_lang.Size = new global::System.Drawing.Size(16, 16);
			this.english_lang.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.english_lang.TabIndex = 1033;
			this.english_lang.TabStop = false;
			this.game_status_bar.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.game_status_bar.BaseColor = global::System.Drawing.Color.Transparent;
			this.game_status_bar.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.game_status_bar.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.game_status_bar.ForeColor = global::System.Drawing.Color.White;
			this.game_status_bar.Location = new global::System.Drawing.Point(0, 442);
			this.game_status_bar.Name = "game_status_bar";
			this.game_status_bar.RectColor = global::System.Drawing.Color.Red;
			this.game_status_bar.ShowTimeDate = false;
			this.game_status_bar.Size = new global::System.Drawing.Size(963, 23);
			this.game_status_bar.TabIndex = 1037;
			this.game_status_bar.Text = "Game Status: Game not Found. Run Dishonored.exe";
			this.game_status_bar.TextColor = global::System.Drawing.Color.White;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(3, 13);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(23, 24);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 1032;
			this.PictureBox2.TabStop = false;
			this.trainer_sts_lbl.AutoSize = true;
			this.trainer_sts_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.trainer_sts_lbl.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.trainer_sts_lbl.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.trainer_sts_lbl.ForeColor = global::System.Drawing.Color.Red;
			this.trainer_sts_lbl.Location = new global::System.Drawing.Point(132, 343);
			this.trainer_sts_lbl.Name = "trainer_sts_lbl";
			this.trainer_sts_lbl.Size = new global::System.Drawing.Size(77, 15);
			this.trainer_sts_lbl.TabIndex = 1031;
			this.trainer_sts_lbl.Text = "Trainer Status";
			this.getGameID_lbl.AutoSize = true;
			this.getGameID_lbl.BackColor = global::System.Drawing.Color.Transparent;
			this.getGameID_lbl.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.getGameID_lbl.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.getGameID_lbl.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.getGameID_lbl.Location = new global::System.Drawing.Point(12, 343);
			this.getGameID_lbl.Name = "getGameID_lbl";
			this.getGameID_lbl.Size = new global::System.Drawing.Size(55, 15);
			this.getGameID_lbl.TabIndex = 1003;
			this.getGameID_lbl.Text = "Game ID:";
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(12, 44);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(197, 296);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 10;
			this.PictureBox1.TabStop = false;
			this.FlatClose1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.FlatClose1.BackColor = global::System.Drawing.Color.White;
			this.FlatClose1.BaseColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatClose1.Font = new global::System.Drawing.Font("Marlett", 12f);
			this.FlatClose1.Location = new global::System.Drawing.Point(944, 3);
			this.FlatClose1.Name = "FlatClose1";
			this.FlatClose1.Size = new global::System.Drawing.Size(18, 18);
			this.FlatClose1.TabIndex = 8;
			this.FlatClose1.Text = "FlatClose1";
			this.FlatClose1.TextColor = global::System.Drawing.Color.FromArgb(220, 220, 220);
			this.FlatMini1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.FlatMini1.BackColor = global::System.Drawing.Color.White;
			this.FlatMini1.BaseColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatMini1.Font = new global::System.Drawing.Font("Marlett", 12f);
			this.FlatMini1.Location = new global::System.Drawing.Point(920, 1);
			this.FlatMini1.Name = "FlatMini1";
			this.FlatMini1.Size = new global::System.Drawing.Size(18, 18);
			this.FlatMini1.TabIndex = 6;
			this.FlatMini1.Text = "FlatMini1";
			this.FlatMini1.TextColor = global::System.Drawing.Color.FromArgb(243, 243, 243);
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(963, 465);
			base.Controls.Add(this.FormSkin1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "Form1";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Dishonored - Game of the Year Edition Trainer by SeryogaSK";
			base.TransparencyKey = global::System.Drawing.Color.Fuchsia;
			this.FormSkin1.ResumeLayout(false);
			this.FormSkin1.PerformLayout();
			this.FlatTabControl1.ResumeLayout(false);
			this.trainer_tab.ResumeLayout(false);
			this.md5_tab.ResumeLayout(false);
			this.trn_settings_tab.ResumeLayout(false);
			this.trn_settings_tab.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.german_lang).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.russian_lang).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.english_lang).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x040000CB RID: 203
		private global::System.ComponentModel.IContainer components;
	}
}
